try {
  setTimeout(()=>{
    throw Error('我是错误')
  })
}catch(e){
  console.log("into")
  console.log(e)
}